### ISSUE TITLE
Python 3.4 compatiblity

### ISSUE THREAD

**Issue by hroncok** [meadowfrey/OctoPrint-Dashboard#2]
The only thing that prevent's 3.4 to run this is the missing `json.JSONDecodeError` exception:

https://github.com/meadowfrey/OctoPrint-Dashboard/blob/8e96cdd026e16a9251b24c1fb62487192d1b0ed7/octoprint_dashboard/services/octoprintService.py#L1

In order to make this 3.4 compatible (as 3.4 runs in FIT CTU classrooms), you should probably send a PR to octoclient not to leak this exception, but as a workaround, you can try to get `ValueError` instead (raised by 3.4:

```python
try:
    from json import JSONDecodeError
except ImportError:  # Python 3.4
    JSONDecodeError = ValueError
```

Or (even better) catch `ValueError` [here](https://github.com/meadowfrey/OctoPrint-Dashboard/blob/8e96cdd026e16a9251b24c1fb62487192d1b0ed7/octoprint_dashboard/services/octoprintService.py#L23) instead of `json.JSONDecodeError` (this works thanks to class inheritance).

```python
>>> from json import JSONDecodeError
>>> JSONDecodeError.__base__
<class 'ValueError'>
```

**Comment by ghost** [comment]
fixed with [commit 9d2ff2a5a2daa0b62121d253779515f6b7d647e4](https://github.com/meadowfrey/OctoPrint-Dashboard/commit/9d2ff2a5a2daa0b62121d253779515f6b7d647e4)
